### PR TITLE
Decider

### PR DESCRIPTION
**Pull request by marcosh**
A decider is a pattern [emerged](https://thinkbeforecoding.com/post/2021/12/17/functional-event-sourcing-decider) in the DDD world.

In machines terms, it is a machine which can rebuild its state out of its own outputs

### CODE REVIEW

**Comment by thinkbeforecoding** [comment]
Happy to see you find the pattern useful 😀
The decider itself is not a mealy machine, but you can always create one from a decider.
A mealy machine is
delta:      Q × A -> Q
lambda:  Q × A -> B
While a decider is:
decide:   Q × A -> B
evolve:    Q × B -> Q

(Q is state, A command, B event) 
The notable difference is that it evolve on its output instead of it's input. 
And storing the output to rebuild state enable modifying decide (or lambda) without versioning problems. 

To convert a decider to a mealy machine:
lambda = decide
delta = decide >> evolve
It enables to reuse existing code about mealy machine, but force executing decide twice for each command. 
It's simple enough (and more versatile) to use it directly.

**Comment by marcosh** [comment]
Thanks @thinkbeforecoding for you comment!

> To convert a decider to a mealy machine: lambda = decide delta = decide >> evolve It enables to reuse existing code about mealy machine, but force executing decide twice for each command. It's simple enough (and more versatile) to use it directly.

Not necessarily. Mealy machines can be implemented as just one function `Q -> A -> (B, Q)`. To implement it with a decider, first you compute `decide`, and then you use its result to compute `evolve` and you pair their results, with no recomputation.
Checkout [this implementation](https://github.com/tweag/crem/pull/56/files#diff-3757a0105e285eafd4ad95163532edc210f64fb4a326edcad369b5f2eb4a45bcR43) for more details

`crem` makes things a bit more complicated, since it is tracking information at the type level, and this imposes some restriction on how machines can be implemented

**Comment by thinkbeforecoding** [comment]
True, I forgot this version of mealy machines.
A decider is actually a way to split the production of (Q × B) from (Q × A) in two sub functions.
So it's more fine gained.

**Comment by thinkbeforecoding** [comment]
My usual definition however is to return a list of events.
This way there is a generic way to represent 'no output' with an empty list. It avoids defining a different 'no output' value in each B. 
And it also make composition more natural as you can concat outputs of different deciders together.
Composition produce a list of unions of Bx | By but it would not generically remove 'no output' from the list.
Conceptually it's equivalent but using lists is simpler.

**Comment by marcosh** [comment]
> My usual definition however is to return a list of events. This way there is a generic way to represent 'no output' with an empty list. It avoids defining a different 'no output' value in each B. And it also make composition more natural as you can concat outputs of different deciders together. Composition produce a list of unions of Bx | By but it would not generically remove 'no output' from the list. Conceptually it's equivalent but using lists is simpler.

In the context of `crem`, returning a list of events is problematic, because you need to state explicitly on which new state you end up in your `evolve` function. Given a state and one single event, it's easy to say explicitly which is the new state, while that is hard to do if you need to fold over a list of events.
This is required by the fact that I'm checking at the type level that only allowed (by a specification provided by the topology of the machine) state transitions are performed.

**Comment by shinzui** [comment]
@marcosh, why did you abandon this branch?

**Comment by marcosh** [comment]
> @marcosh, why did you abandon this branch?

don't really remember... possibly because its content was already implemented (see https://github.com/marcosh/crem/blob/main/examples/Crem/Example/Uno.hs and https://github.com/marcosh/crem/blob/main/src/Crem/Decider.hs)

**Comment by shinzui** [comment]
>  possibly because its content was already implemented

Thanks.

**Pull request closed without merging**
